version: '3.8'

services:
  dolphinscheduler:
    image: apache/dolphinscheduler-standalone-server:3.2.2
    container_name: dolphinscheduler-standalone-server
    ports:
      - "12345:12345"
      - "25333:25333"
      - "5005:5005"
    environment:
      - JAVA_OPTS=-Xdebug -Xrunjdwp:transport=dt_socket,address=5005,server=y,suspend=n
    restart: unless-stopped