version: '3.8'

services:
  pinot:
    image: apachepinot/pinot:1.1.0
    command: QuickStart -type batch
    ports:
      - "2123:2123"
      - "9000:9000"
      - "8000:8000"
      - "7050:7050"
      - "6000:6000"
      - "5005:5005"  # 映射JVM调试端口
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005